### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ItDev-Angel/grid-template#1]
1)
Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/172376284-6921bd4d-7025-4f80-b23e-fdec4cff5bf8.png)

2)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/172376543-94006256-848a-4fd7-a4f2-0ca84906dd42.png)

3)
дергается при уходе курсора
![image](https://user-images.githubusercontent.com/8464662/172376748-8f25c74d-6e6a-4b7c-8ffd-15f49b793d13.png)

4)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/172376934-ae15de55-2e3c-4658-85ae-5b9308383945.png)

**Comment by ItDev-Angel** [comment]
https://itdev-angel.github.io/grid-template/
